name: Django CI/CD Pipeline

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            echo "Using existing .env file..."

            echo "Pulling Docker images..."
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}

            if [ $(sudo docker ps -aq -f name=myapp) ]; then
                echo "Stopping existing container..."
                sudo docker stop myapp

                echo "Removing existing container..."
                sudo docker rm myapp
            else
                echo "No existing container to stop or remove."
            fi

            echo "Starting new container..."
            sudo docker run -d --name myapp -p 80:8000 --env-file .env ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}

            echo "Deployment complete."
          EOF