name: Django CI/CD Pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8

      - name: Run flake8
        run: flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt 

      - name: Run tests
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Переходим в папку проекта или клонируем его, если он еще не существует
            if [ ! -d "Habit_tracker" ]; then
              git clone https://github.com/yourusername/your-repo.git Habit_tracker
            fi
            
            cd Habit_tracker || exit 1;  # Переход в директорию, если не удалось - выход с ошибкой
            echo "Текущая директория: $(pwd)";  # Вывод текущей директории для отладки
            git checkout main;
            git pull;
          
            # Остановка и удаление старых контейнеров
            docker-compose --file docker-compose.yaml down;
          
            # Запуск новых контейнеров
            docker-compose --file docker-compose.yaml up -d;
          
            # Очистка неиспользуемых образов и контейнеров
            docker system prune --all --force;
          EOF